//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expressions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expressions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the absolute value of x..
        /// </summary>
        internal static string ABS {
            get {
                return ResourceManager.GetString("ABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add x days to the provided date, use a negative number to subtract..
        /// </summary>
        internal static string ADDDAYS {
            get {
                return ResourceManager.GetString("ADDDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add x months to the provided date, use a negative number to subtract..
        /// </summary>
        internal static string ADDMONTHS {
            get {
                return ResourceManager.GetString("ADDMONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add x years to the provided date, use a negative number to subtract..
        /// </summary>
        internal static string ADDYEARS {
            get {
                return ResourceManager.GetString("ADDYEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if both expr1 and expr2 are true..
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combines two strings, works the same as the + operator for strings.  However if both parameters are numbers, CONCAT will force the numbers to be treated as strings and joined together, while the + operator will add numbers..
        /// </summary>
        internal static string CONCAT {
            get {
                return ResourceManager.GetString("CONCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the cosine of x..
        /// </summary>
        internal static string COS {
            get {
                return ResourceManager.GetString("COS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a date created using the year, month, and day values..
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days difference between date 2 and date 1. Always returns a value measured in whole days..
        /// </summary>
        internal static string DATEDIFF {
            get {
                return ResourceManager.GetString("DATEDIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the numeric days portion of a date..
        /// </summary>
        internal static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a number to a string using the provided format. 0 = Zero placeholder, # = digit placeholder.  Example #,##0.00 will format a number to always have two decimal places and will use a comma as a thousands separator..
        /// </summary>
        internal static string FORMATNUMBER {
            get {
                return ResourceManager.GetString("FORMATNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs an If operation.  If expr evaluates to true, then trueValue is returned, else falseValue is returned..
        /// </summary>
        internal static string IF {
            get {
                return ResourceManager.GetString("IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns true if value is a valid date..
        /// </summary>
        internal static string ISDATE {
            get {
                return ResourceManager.GetString("ISDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns true if expr is not null.
        /// </summary>
        internal static string ISNOTNULL {
            get {
                return ResourceManager.GetString("ISNOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns true if expr is null.
        /// </summary>
        internal static string ISNULL {
            get {
                return ResourceManager.GetString("ISNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns true if value is a valid number..
        /// </summary>
        internal static string ISNUMBER {
            get {
                return ResourceManager.GetString("ISNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the left most len characters from the string s..
        /// </summary>
        internal static string LEFT {
            get {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the length of string s..
        /// </summary>
        internal static string LENGTH {
            get {
                return ResourceManager.GetString("LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup table function.  Looks for the value in lookup table, if the lookup table exists and value is found, the lookup result is returned.  If the table does not exist or value is not found, then default is returned..
        /// </summary>
        internal static string LOOKUP {
            get {
                return ResourceManager.GetString("LOOKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert entire string to lower case letters..
        /// </summary>
        internal static string LOWER {
            get {
                return ResourceManager.GetString("LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the larger of two numbers x and y..
        /// </summary>
        internal static string MAX {
            get {
                return ResourceManager.GetString("MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the smaller of two numbers x and y..
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the numeric months portion of a date..
        /// </summary>
        internal static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns True when the operand is False or False when the operand is True..
        /// </summary>
        internal static string NOT {
            get {
                return ResourceManager.GetString("NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds two numbers or combines two strings into a single string..
        /// </summary>
        internal static string op_Addition {
            get {
                return ResourceManager.GetString("op_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division operation.  May use ÷ or / symbols to indicate division..
        /// </summary>
        internal static string op_Division {
            get {
                return ResourceManager.GetString("op_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compares two values and returns true if both are equal..
        /// </summary>
        internal static string op_Equal {
            get {
                return ResourceManager.GetString("op_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compares two values and returns true if the first value is larger than the second value..
        /// </summary>
        internal static string op_GreaterThan {
            get {
                return ResourceManager.GetString("op_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compares two values and returns true if the first value is smaller than the second value..
        /// </summary>
        internal static string op_LessThan {
            get {
                return ResourceManager.GetString("op_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulitplication.
        /// </summary>
        internal static string op_Multiplication {
            get {
                return ResourceManager.GetString("op_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns true if two values are not equal.  May use the following symbols to indicate not equal:  ≠, &lt;&gt;, !=.
        /// </summary>
        internal static string op_NotEqual {
            get {
                return ResourceManager.GetString("op_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent..
        /// </summary>
        internal static string op_Power {
            get {
                return ResourceManager.GetString("op_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction..
        /// </summary>
        internal static string op_Subtraction {
            get {
                return ResourceManager.GetString("op_Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if either expr1 or expr2 or both are true..
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces the characters oldValue with newValue within the string s..
        /// </summary>
        internal static string REPLACE {
            get {
                return ResourceManager.GetString("REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the right most len characters from the string str..
        /// </summary>
        internal static string RIGHT {
            get {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds x to the nearest number of specified number of digits.  Specify d as 0 to round to the nearest whole number..
        /// </summary>
        internal static string ROUND {
            get {
                return ResourceManager.GetString("ROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the sine of x..
        /// </summary>
        internal static string SIN {
            get {
                return ResourceManager.GetString("SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the square root of x..
        /// </summary>
        internal static string SQRT {
            get {
                return ResourceManager.GetString("SQRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a portion of the string s, starting at position x and containing y characters.  The first character in the string is position 0. .
        /// </summary>
        internal static string SUBSTRING {
            get {
                return ResourceManager.GetString("SUBSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns today&apos;s date.  Date is based on the timezone of the computer running the calculation..
        /// </summary>
        internal static string TODAY {
            get {
                return ResourceManager.GetString("TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trims all leading and trailing spaces off of string s..
        /// </summary>
        internal static string TRIM {
            get {
                return ResourceManager.GetString("TRIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative sign in front of a number..
        /// </summary>
        internal static string UnaryMinus {
            get {
                return ResourceManager.GetString("UnaryMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown operation..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert entire string to upper case letters..
        /// </summary>
        internal static string UPPER {
            get {
                return ResourceManager.GetString("UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the numeric years portion of a date..
        /// </summary>
        internal static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
